set_xmakever("2.3.2")
add_rules("mode.debug", "mode.release")
add_requires("libxmake", "lief")
target("app_injector")
    add_rules("xmake.cli")
    add_files("src/lni/*.c")
    add_packages("libxmake", "lief")
